Parameters:
  stageName:
    Type: String
    Default: v1
    Description: Stage name exposed in the invoke URL

AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com # mean only lambda can assume it
            Action: sts:AssumeRole
      ManagedPolicyArns:                 # Basic permissions to write logs to CloudWatch, in case you want to use that in the future.
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole


  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: python3.12
      Handler: index.handler
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              return {
                  "statusCode": 200,
                  "headers": {"Content-Type": "application/json"},
                  "body": json.dumps({"message": "Hello world!"})
              }
      Tags:
        - Key: Name
          Value: MyLambdaFunction

